project_id = "slthyxqruhfuyfmextwr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv4"
port = 54323

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54329
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[functions.get-transaction-by-token]
verify_jwt = false

[functions.mark-payment-authorized]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.join-transaction]
verify_jwt = true

[functions.process-dispute]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.create-stripe-account]
verify_jwt = true

[functions.sync-stripe-payments]
verify_jwt = true

[functions.clean-old-users]
verify_jwt = true

[functions.fix-blocked-transaction]
verify_jwt = true

[functions.process-validation-deadline]
verify_jwt = false

[functions.process-validation-deadline.cron]
schedule = "*/10 * * * *"

[functions.send-validation-reminders]
verify_jwt = false

[functions.delete-user-account]
verify_jwt = true

[functions.release-funds]
verify_jwt = true

[functions.process-expired-payment-deadlines]
verify_jwt = false

[functions.create-dispute]
verify_jwt = true

[functions.request-date-change]
verify_jwt = true

[functions.respond-to-date-change]
verify_jwt = true

[functions.respond-to-dispute]
verify_jwt = true

[functions.process-dispute-deadlines]
verify_jwt = false

[functions.validate-stripe-accounts]
verify_jwt = true

[functions.process-automatic-transfer]
verify_jwt = true

[functions.check-stripe-account-status]
verify_jwt = true

[functions.sync-stripe-customers]
verify_jwt = true

[functions.create-payment-checkout]
verify_jwt = true

[functions.create-transaction]
verify_jwt = true

[functions.get-user-emails]
verify_jwt = true

[functions.update-stripe-account-info]
verify_jwt = true

[functions.create-proposal]
verify_jwt = true

[functions.accept-proposal]
verify_jwt = true

[functions.reject-proposal]
verify_jwt = true

[functions.create-admin-proposal]
verify_jwt = true

[functions.validate-admin-proposal]
verify_jwt = true

[functions.renew-expired-transaction]
verify_jwt = true

[functions.send-transaction-message]
verify_jwt = true

[functions.mark-messages-read]
verify_jwt = true

[functions.delete-expired-transaction]
verify_jwt = true

[functions.admin-get-transaction]
verify_jwt = true

[edge_runtime]
enabled = true
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
gw_port = 54329

# [experimental]
# orioledb_version = ""
# s3_host = "localhost" 
# s3_region = "local"
# Commented out to avoid false security warnings - these are local dev keys only
# s3_access_key_id = "625729a08b95bf1b7ff351a663f3a23c"
# s3_secret_access_key = "850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6eda37307425907"