project_id = "slthyxqruhfuyfmextwr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323
log_level = "info"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
port = 54329
policy = "per_worker"
inspector_port = 54330

[functions.accept-proposal]
verify_jwt = true

[functions.accept-quote]
verify_jwt = true

[functions.attach-quote-to-user]
verify_jwt = true

[functions.admin-delete-transaction]
verify_jwt = true

[functions.admin-dispute-actions]
verify_jwt = true

[functions.admin-get-transaction]
verify_jwt = true

[functions.check-stripe-account-status]
verify_jwt = true

[functions.clean-old-users]
verify_jwt = true


[functions.confirm-transaction-date]
verify_jwt = true

[functions.create-admin-proposal]
verify_jwt = true

[functions.create-dispute]
verify_jwt = true

[functions.create-payment-checkout]
verify_jwt = true

[functions.create-payment-intent]
verify_jwt = true

[functions.create-proposal]
verify_jwt = true

[functions.create-quote]
verify_jwt = true

[functions.create-stripe-account]
verify_jwt = true

[functions.create-stripe-customer]
verify_jwt = true

[functions.create-transaction]
verify_jwt = true

[functions.delete-expired-transaction]
verify_jwt = true

[functions.delete-user-account]
verify_jwt = true

[functions.export-user-data]
verify_jwt = true

[functions.fix-blocked-transaction]
verify_jwt = true

[functions.fix-reactivated-transactions]
verify_jwt = false

[functions.fix-resolved-disputes]
verify_jwt = false

[functions.force-escalate-dispute]
verify_jwt = true

[functions.gdpr-data-retention-cleanup]
verify_jwt = false

[functions.generate-annual-report]
verify_jwt = true

[functions.generate-invoice-number]
verify_jwt = true

[functions.get-invoice-data]
verify_jwt = true

[functions.get-quote-by-token]
verify_jwt = false

[functions.get-transaction-by-token]
verify_jwt = false

[functions.get-transactions-enriched]
verify_jwt = true

[functions.get-user-emails]
verify_jwt = true

[functions.join-transaction]
verify_jwt = true

[functions.mark-messages-read]
verify_jwt = true

[functions.mark-payment-authorized]
verify_jwt = true

[functions.mark-quote-as-viewed]
verify_jwt = true

[functions.process-automatic-transfer]
verify_jwt = true

[functions.process-dispute]
verify_jwt = true

[functions.process-dispute-deadlines]
verify_jwt = false

[functions.process-expired-payment-deadlines]
verify_jwt = false

[functions.process-validation-deadline]
verify_jwt = false

[functions.refresh-counterparty-stripe-status]
verify_jwt = true

[functions.reject-proposal]
verify_jwt = true

[functions.release-funds]
verify_jwt = true

[functions.renew-expired-transaction]
verify_jwt = true

[functions.request-date-change]
verify_jwt = true

[functions.resend-quote-email]
verify_jwt = true

[functions.respond-to-date-change]
verify_jwt = true

[functions.respond-to-dispute]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.send-payment-reminders]
verify_jwt = false

[functions.send-validation-reminders]
verify_jwt = false

[functions.sync-stripe-customers]
verify_jwt = false

[functions.sync-stripe-payments]
verify_jwt = false

[functions.update-quote]
verify_jwt = true

[functions.update-stripe-account-info]
verify_jwt = true

[functions.validate-admin-proposal]
verify_jwt = true

[functions.validate-stripe-accounts]
verify_jwt = true

[edge_runtime]
enabled = true
inspector_port = 8083

[analytics]
enabled = false
port = 54327
vector_port = 54328
gw_port = 54329

# [experimental]
# orioledb_version = ""
# s3_host = "localhost" 
# s3_region = "local"
# Commented out to avoid false security warnings - these are local dev keys only
# s3_access_key_id = "625729a08b95bf1b7ff351a663f3a23c"
# s3_secret_access_key = "850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6eda37307425907"