name: Deploy to Production

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy to Lovable
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build

      - name: Deploy to Lovable
        run: |
          echo "✅ Code pushed to main branch"
          echo "🚀 Lovable will automatically deploy this commit"
          echo "📊 Monitor deployment at: https://lovable.app"

      - name: Create deployment notification
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.repos.createCommitComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
              body: '🚀 Deployment to production initiated via Lovable'
            })

  notify:
    name: Notify Deployment
    runs-on: ubuntu-latest
    needs: deploy
    if: success()
    
    steps:
      - name: Send success notification
        run: |
          echo "✅ Deployment successful!"
          echo "🎉 RivvLock is now live in production"
